/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.calculadora.telas;

import DTO.OrcamentoDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author corte
 */
public class CalculadoraItems extends javax.swing.JFrame {

    private String valorHora;

    public String getValorHora() {
        return valorHora;
    }

    public void setValorHora(String valorHora) {
        this.valorHora = valorHora;
    }
    
    
    /**
     * Creates new form CalculadoraItems
     */
    public CalculadoraItems() {
        initComponents();

        txtHorasTotais.setText("0");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbTipoItem = new javax.swing.JComboBox<>();
        cbDificuldade = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtHorasTotais = new javax.swing.JTextField();
        btnSelecionar = new javax.swing.JToggleButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Selecione o Tipo de Item do Sistema");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Selecione a Dificuldade");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("Calculadora de itens");

        cbTipoItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------  Selecione o tipo de Item  --------", "Telas com entradas e saídas de dados", "Telas de consultas com informação de dados", "Gravação de dados" }));

        cbDificuldade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Tempo estimado (horas): ");

        txtHorasTotais.setEditable(false);
        txtHorasTotais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorasTotaisActionPerformed(evt);
            }
        });

        btnSelecionar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(222, 222, 222))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cbTipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHorasTotais, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHorasTotais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        selecionaTipoItem();


    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void txtHorasTotaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorasTotaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorasTotaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CalculadoraItems().setVisible(true);
        });
    }

    public void selecionaTipoItem() {
        String tipoItem = cbTipoItem.getSelectedItem().toString();
        String dificuldade = cbDificuldade.getSelectedItem().toString();
        int tipoItemNum = 0;
        int horas = 0;
        int horasTotais = Integer.parseInt(txtHorasTotais.getText());

        int dificuldadeNum = Integer.parseInt(dificuldade);

        if (tipoItem.equals("Telas com entradas e saídas de dados")) {
            tipoItemNum = 1;
        }
        if (tipoItem.equals("Telas de consultas com informação de dados")) {
            tipoItemNum = 2;
        }
        if (tipoItem.equals("Gravação de dados")) {
            tipoItemNum = 3;
        }
        if (tipoItemNum == 1 && dificuldadeNum == 1) {
            horas = 8;
        }
        if (tipoItemNum == 1 && dificuldadeNum == 2) {
            horas = 12;
        }
        if (tipoItemNum == 1 && dificuldadeNum == 3) {
            horas = 16;
        }

        if (tipoItemNum == 2 && dificuldadeNum == 1) {
            horas = 4;
        }
        if (tipoItemNum == 2 && dificuldadeNum == 2) {
            horas = 6;
        }
        if (tipoItemNum == 2 && dificuldadeNum == 3) {
            horas = 8;
        }

        if (tipoItemNum == 3 && dificuldadeNum == 1) {
            horas = 16;
        }
        if (tipoItemNum == 3 && dificuldadeNum == 2) {
            horas = 24;
        }
        if (tipoItemNum == 3 && dificuldadeNum == 3) {
            horas = 36;
        }

        if (tipoItemNum == 0) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente.");
        } else {

            String horasTexto = String.valueOf(horas);

            txtHorasTotais.setText(horasTexto);

            horasTotais = horasTotais + horas;

            txtHorasTotais.setText(String.valueOf(horasTotais));

            OrcamentoDTO orcamentoDTO = new OrcamentoDTO();
            orcamentoDTO.setTotalHoras(horasTotais);

            int continuar = JOptionPane.showConfirmDialog(null, horas + " horas adicionadas. Deseja selecionar mais itens?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (continuar == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Serão gastas em média " + horasTotais + " horas para realizar o programa.");

                Orcamento orcamento = new Orcamento();
                orcamento.setVisible(true);
                orcamento.txtHorasTotais.setText(String.valueOf(orcamentoDTO.getTotalHoras()));
                orcamento.txtValorHora.setText(valorHora);
                this.dispose();

            }

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSelecionar;
    private javax.swing.JComboBox<String> cbDificuldade;
    private javax.swing.JComboBox<String> cbTipoItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtHorasTotais;
    // End of variables declaration//GEN-END:variables
}
